apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-vol
  labels:
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
        name: nginx-pod
        labels:
          app: nginx
    spec:
        containers:
        - name: mynginx
          image: nginx:1.19
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
        volumes:
        - name: cache-volume
          emptyDir: {}