apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
        name: nginx-pod
        labels:
          app: nginx
    spec:
        containers:
        - name: mynginx
          image: nginx:1.19
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: /test-pd
              name: clarus-pv-storage
        volumes:
          - name: clarus-pv-storage
            persistentVolumeClaim:
              claimName: clarus-pv-claim